/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boarding_house;

import javax.swing.*;
import java.sql.*;

/**
 *
 * @author ASUS
 */
public class Rooms extends javax.swing.JFrame {

    /**
     * Creates new form Rooms
     */
    public Rooms() {
        initComponents();
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setWidth(0);
        loadRoomsTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnDasboard = new javax.swing.JButton();
        btnTenants = new javax.swing.JButton();
        btnRooms = new javax.swing.JButton();
        btnPayments = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnHistory1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ben.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 255));
        jLabel2.setText("BOARDING HOUSE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Management System");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 230, 20));

        btnDasboard.setBackground(new java.awt.Color(255, 204, 255));
        btnDasboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDasboard.setForeground(new java.awt.Color(102, 0, 102));
        btnDasboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home (2).png"))); // NOI18N
        btnDasboard.setText("Dashboard");
        btnDasboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDasboard.setIconTextGap(15);
        btnDasboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDasboardActionPerformed(evt);
            }
        });
        jPanel1.add(btnDasboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 170, -1));

        btnTenants.setBackground(new java.awt.Color(255, 204, 255));
        btnTenants.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTenants.setForeground(new java.awt.Color(102, 0, 102));
        btnTenants.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/person.png"))); // NOI18N
        btnTenants.setText("Tenants");
        btnTenants.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTenants.setIconTextGap(15);
        btnTenants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTenantsActionPerformed(evt);
            }
        });
        jPanel1.add(btnTenants, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 170, -1));

        btnRooms.setBackground(new java.awt.Color(255, 204, 255));
        btnRooms.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRooms.setForeground(new java.awt.Color(102, 0, 102));
        btnRooms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door (2).png"))); // NOI18N
        btnRooms.setText("Rooms");
        btnRooms.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRooms.setIconTextGap(15);
        btnRooms.setInheritsPopupMenu(true);
        btnRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomsActionPerformed(evt);
            }
        });
        jPanel1.add(btnRooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 170, -1));

        btnPayments.setBackground(new java.awt.Color(255, 204, 255));
        btnPayments.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPayments.setForeground(new java.awt.Color(102, 0, 102));
        btnPayments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/online-payment.png"))); // NOI18N
        btnPayments.setText("Payments");
        btnPayments.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPayments.setIconTextGap(15);
        btnPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentsActionPerformed(evt);
            }
        });
        jPanel1.add(btnPayments, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 170, -1));

        btnlogout.setBackground(new java.awt.Color(255, 204, 255));
        btnlogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(102, 0, 102));
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnlogout.setIconTextGap(15);
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 170, -1));

        btnHistory1.setBackground(new java.awt.Color(255, 204, 255));
        btnHistory1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHistory1.setForeground(new java.awt.Color(102, 0, 102));
        btnHistory1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/history.png"))); // NOI18N
        btnHistory1.setText("History");
        btnHistory1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHistory1.setIconTextGap(15);
        btnHistory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistory1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnHistory1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 520));

        jPanel2.setBackground(new java.awt.Color(255, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Rooms");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 760, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 153));
        jLabel5.setText("Room Number:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 170, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 153));
        jLabel6.setText("Capacity:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 153));
        jLabel7.setText("Status:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 153));
        jLabel8.setText("Gender:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 170, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 170, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Available", "Not Available" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 170, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Room #", "Capacity", "Gender", "Occupied", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 660, 170));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 140, 40));

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("DELETE ROOM");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 140, 40));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("ADD ROOM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 140, 40));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("UPDATE ROOM");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 140, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 750, 520));

        setSize(new java.awt.Dimension(997, 556));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDasboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDasboardActionPerformed
        this.setVisible(false);
        Home object = new Home();
        object.setVisible(true);
    }//GEN-LAST:event_btnDasboardActionPerformed

    private void btnTenantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTenantsActionPerformed
        this.setVisible(false);
        Tenants object = new Tenants();
        object.setVisible(true);
    }//GEN-LAST:event_btnTenantsActionPerformed

    private void btnRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomsActionPerformed
        this.setVisible(false);
        Rooms object = new Rooms();
        object.setVisible(true);
    }//GEN-LAST:event_btnRoomsActionPerformed

    private void btnPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentsActionPerformed
        this.setVisible(false);
        Payment object = new Payment();
        object.setVisible(true);
    }//GEN-LAST:event_btnPaymentsActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout Boarding House", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION){
            this.setVisible(false);
            Login object = new Login();
            object.setVisible(true);

        }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnHistory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistory1ActionPerformed
        this.setVisible(false);
        History object = new History();
        object.setVisible(true);
    }//GEN-LAST:event_btnHistory1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();

    if (row >= 0) {
        try {
            jTextField1.setText(jTable1.getValueAt(row, 1).toString());
            jSpinner1.setValue(Integer.parseInt(jTable1.getValueAt(row, 2).toString()));

            String gender = jTable1.getValueAt(row, 3).toString();
            jComboBox1.setSelectedItem(
                    gender.substring(0, 1).toUpperCase() + gender.substring(1)
            );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error selecting room: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        clearRoomFields();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        deleteRoom();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addRoom();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        updateRoom();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    private void logHistory(String module, String action, String details) {
    try {
        java.sql.Connection conn = DBConnection.getConnection();

        String sql = "INSERT INTO history (tenant_id, module, action_type, details) VALUES (NULL, ?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, module);
        pst.setString(2, action);
        pst.setString(3, details);

        pst.executeUpdate();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "History Log Error: " + e.getMessage());
    }
}
    private void loadRoomsTable() {
    try {
        javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        java.sql.Connection conn = DBConnection.getConnection();

        String sql = "SELECT * FROM rooms ORDER BY id DESC";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("room_number"),
                rs.getInt("capacity"),
                rs.getString("gender"),
                rs.getInt("occupied"),
                rs.getString("status")
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading rooms: " + e.getMessage());
    }
}
    private void clearRoomFields() {
    jTextField1.setText("");
    jSpinner1.setValue(0);
    jComboBox1.setSelectedIndex(0);
    jTable1.clearSelection();
}
    private void addRoom() {
    try {
        String roomNumber = jTextField1.getText().trim();
        int capacity = (int) jSpinner1.getValue();
        String gender = jComboBox1.getSelectedItem().toString();

        if (roomNumber.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter room number.");
            return;
        }

        if (capacity <= 0) {
            JOptionPane.showMessageDialog(this, "Capacity must be greater than 0.");
            return;
        }

        if (gender.equals("Select")) {
            JOptionPane.showMessageDialog(this, "Please select gender.");
            return;
        }

        java.sql.Connection conn = DBConnection.getConnection();

        String checkSql = "SELECT id FROM rooms WHERE room_number=?";
        PreparedStatement checkPst = conn.prepareStatement(checkSql);
        checkPst.setString(1, roomNumber);
        ResultSet rs = checkPst.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(this, "Room number already exists.");
            return;
        }

        String sql = "INSERT INTO rooms (room_number, capacity, gender, occupied, status) "
                + "VALUES (?, ?, ?, 0, 'Available')";

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, roomNumber);
        pst.setInt(2, capacity);
        pst.setString(3, gender.toLowerCase());

        pst.executeUpdate();

        logHistory("Rooms", "ADD", "Added Room " + roomNumber + " with capacity " + capacity);

        JOptionPane.showMessageDialog(this, "Room added successfully.");

        loadRoomsTable();
        clearRoomFields();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error adding room: " + e.getMessage());
    }
}
    
    
    
    private void updateRoom() {
    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a room to update.");
        return;
    }

    try {
        int roomId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
        int occupied = Integer.parseInt(jTable1.getValueAt(selectedRow, 4).toString());

        String roomNumber = jTextField1.getText().trim();
        int capacity = (int) jSpinner1.getValue();
        String gender = jComboBox1.getSelectedItem().toString();

        if (roomNumber.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter room number.");
            return;
        }

        if (capacity <= 0) {
            JOptionPane.showMessageDialog(this, "Capacity must be greater than 0.");
            return;
        }

        if (capacity < occupied) {
            JOptionPane.showMessageDialog(this, "Capacity cannot be lower than occupied tenants.");
            return;
        }

        if (gender.equals("Select")) {
            JOptionPane.showMessageDialog(this, "Please select gender.");
            return;
        }

        String status = occupied >= capacity ? "Not Available" : "Available";

        java.sql.Connection conn = DBConnection.getConnection();

        String checkSql = "SELECT id FROM rooms WHERE room_number=? AND id<>?";
        PreparedStatement checkPst = conn.prepareStatement(checkSql);
        checkPst.setString(1, roomNumber);
        checkPst.setInt(2, roomId);
        ResultSet rs = checkPst.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(this, "Another room already uses this room number.");
            return;
        }

        String sql = "UPDATE rooms SET room_number=?, capacity=?, gender=?, status=? WHERE id=?";

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, roomNumber);
        pst.setInt(2, capacity);
        pst.setString(3, gender.toLowerCase());
        pst.setString(4, status);
        pst.setInt(5, roomId);

        pst.executeUpdate();

        logHistory("Rooms", "UPDATE", "Updated Room " + roomNumber + ". Capacity: " + capacity + ", Status: " + status);

        JOptionPane.showMessageDialog(this, "Room updated successfully.");

        loadRoomsTable();
        clearRoomFields();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error updating room: " + e.getMessage());
    }
}
    
    private void deleteRoom() {
    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a room to delete.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this room?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    try {
        int roomId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
        String roomNumber = jTable1.getValueAt(selectedRow, 1).toString();
        int occupied = Integer.parseInt(jTable1.getValueAt(selectedRow, 4).toString());

        if (occupied > 0) {
            JOptionPane.showMessageDialog(this, "Cannot delete room. There are still tenants assigned to it.");
            return;
        }

        java.sql.Connection conn = DBConnection.getConnection();

        String sql = "DELETE FROM rooms WHERE id=?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, roomId);

        pst.executeUpdate();

        logHistory("Rooms", "DELETE", "Deleted Room " + roomNumber);

        JOptionPane.showMessageDialog(this, "Room deleted successfully.");

        loadRoomsTable();
        clearRoomFields();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error deleting room: " + e.getMessage());
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDasboard;
    private javax.swing.JButton btnHistory1;
    private javax.swing.JButton btnPayments;
    private javax.swing.JButton btnRooms;
    private javax.swing.JButton btnTenants;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
