/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boarding_house;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author ASUS
 */
public class Tenants extends javax.swing.JFrame {

    /**
     * Creates new form Tenants
     */
    public Tenants() {
        initComponents();
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
    jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
    jTable1.getColumnModel().getColumn(0).setWidth(0);
        loadTenantsTable();
        loadRoomsToComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnDasboard = new javax.swing.JButton();
        btnTenants = new javax.swing.JButton();
        btnRooms = new javax.swing.JButton();
        btnPayments = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnHistory1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jTextField4 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ben.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 255));
        jLabel2.setText("BOARDING HOUSE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Management System");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 230, 20));

        btnDasboard.setBackground(new java.awt.Color(255, 204, 255));
        btnDasboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDasboard.setForeground(new java.awt.Color(102, 0, 102));
        btnDasboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home (2).png"))); // NOI18N
        btnDasboard.setText("Dashboard");
        btnDasboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDasboard.setIconTextGap(15);
        btnDasboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDasboardActionPerformed(evt);
            }
        });
        jPanel1.add(btnDasboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 170, -1));

        btnTenants.setBackground(new java.awt.Color(255, 204, 255));
        btnTenants.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTenants.setForeground(new java.awt.Color(102, 0, 102));
        btnTenants.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/person.png"))); // NOI18N
        btnTenants.setText("Tenants");
        btnTenants.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTenants.setIconTextGap(15);
        btnTenants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTenantsActionPerformed(evt);
            }
        });
        jPanel1.add(btnTenants, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 170, -1));

        btnRooms.setBackground(new java.awt.Color(255, 204, 255));
        btnRooms.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRooms.setForeground(new java.awt.Color(102, 0, 102));
        btnRooms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door (2).png"))); // NOI18N
        btnRooms.setText("Rooms");
        btnRooms.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRooms.setIconTextGap(15);
        btnRooms.setInheritsPopupMenu(true);
        btnRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomsActionPerformed(evt);
            }
        });
        jPanel1.add(btnRooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 170, -1));

        btnPayments.setBackground(new java.awt.Color(255, 204, 255));
        btnPayments.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPayments.setForeground(new java.awt.Color(102, 0, 102));
        btnPayments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/online-payment.png"))); // NOI18N
        btnPayments.setText("Payments");
        btnPayments.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPayments.setIconTextGap(15);
        btnPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentsActionPerformed(evt);
            }
        });
        jPanel1.add(btnPayments, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 170, -1));

        btnlogout.setBackground(new java.awt.Color(255, 204, 255));
        btnlogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(102, 0, 102));
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnlogout.setIconTextGap(15);
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 170, -1));

        btnHistory1.setBackground(new java.awt.Color(255, 204, 255));
        btnHistory1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHistory1.setForeground(new java.awt.Color(102, 0, 102));
        btnHistory1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/history.png"))); // NOI18N
        btnHistory1.setText("History");
        btnHistory1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHistory1.setIconTextGap(15);
        btnHistory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistory1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnHistory1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 520));

        jPanel2.setBackground(new java.awt.Color(255, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Name:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Contact", "Address", "Gender", "Age", "Room_ID", "Check-in", "Check_out", "Months STayed", "Payment Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 1000, 230));

        jLabel6.setText("Contact:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel7.setText("Address:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jLabel8.setText("Check-in:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        jLabel9.setText("Room_id:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        jLabel10.setText("Gender:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jLabel11.setText("Payment Status:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, -1, -1));

        jLabel12.setText("Age:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, -1, -1));

        jLabel13.setText("Check_Out");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 114, -1, 30));

        jLabel14.setText("Months Stayed:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Tenants");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1020, 10));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 170, -1));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 160, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 130, -1));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 170, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox2.setName("Select"); // NOI18N
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 130, -1));
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 100, -1));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 160, -1));
        jPanel2.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 100, -1));
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, 80, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Paid", "Unpaid" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 120, 80, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("ADD TENANTS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 190, 40));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("UPDATE TENANT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 190, 40));

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("DELETE TENANT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 190, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 190, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 1030, 520));

        setSize(new java.awt.Dimension(1274, 557));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDasboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDasboardActionPerformed
        this.setVisible(false);
        Home object = new Home();
        object.setVisible(true);
    }//GEN-LAST:event_btnDasboardActionPerformed

    private void btnTenantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTenantsActionPerformed
        this.setVisible(false);
        Tenants object = new Tenants();
        object.setVisible(true);
    }//GEN-LAST:event_btnTenantsActionPerformed

    private void btnRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomsActionPerformed
        this.setVisible(false);
        Rooms object = new Rooms();
        object.setVisible(true);
    }//GEN-LAST:event_btnRoomsActionPerformed

    private void btnPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentsActionPerformed
        this.setVisible(false);
        Payment object = new Payment();
        object.setVisible(true);
    }//GEN-LAST:event_btnPaymentsActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout Boarding House", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION){
            this.setVisible(false);
            Login object = new Login();
            object.setVisible(true);

        }

    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnHistory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistory1ActionPerformed
        this.setVisible(false);
        History object = new History();
        object.setVisible(true);
    }//GEN-LAST:event_btnHistory1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addTenant();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        deleteTenant();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       updateTenant();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
                                        
    int row = jTable1.getSelectedRow();

    if (row >= 0) {
        try {
            String name = jTable1.getValueAt(row, 1).toString();
            String contact = jTable1.getValueAt(row, 2).toString();
            String address = jTable1.getValueAt(row, 3).toString();
            String gender = jTable1.getValueAt(row, 4).toString();
            int age = Integer.parseInt(jTable1.getValueAt(row, 5).toString());
            String roomId = jTable1.getValueAt(row, 6).toString();

            java.util.Date checkIn =
                    java.sql.Date.valueOf(jTable1.getValueAt(row, 7).toString());

            java.util.Date checkOut =
                    java.sql.Date.valueOf(jTable1.getValueAt(row, 8).toString());

            int months = Integer.parseInt(jTable1.getValueAt(row, 9).toString());
            String payment = jTable1.getValueAt(row, 10).toString();

            jTextField1.setText(name);
            jTextField3.setText(contact);
            jTextField2.setText(address);
            jComboBox1.setSelectedItem(gender);
            jSpinner1.setValue(age);
            jComboBox2.setSelectedItem(roomId);
            jDateChooser1.setDate(checkIn);
            jDateChooser2.setDate(checkOut);
            jTextField4.setText(String.valueOf(months));
            jComboBox3.setSelectedItem(
                    payment.substring(0, 1).toUpperCase() + payment.substring(1)
            );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading row: " + e.getMessage());
        }
    }


    }//GEN-LAST:event_jTable1MouseClicked
    private void logHistory(int tenantId, String action, String details) {
    try {
        java.sql.Connection conn = DBConnection.getConnection();

        String sql = "INSERT INTO history (tenant_id, action_type, details) VALUES (?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setInt(1, tenantId);
        pst.setString(2, action);
        pst.setString(3, details);

        pst.executeUpdate();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "History Error: " + e.getMessage());
    }
}
    private int calculateMonths(java.util.Date checkIn, java.util.Date checkOut) {
    java.time.LocalDate in = new java.sql.Date(checkIn.getTime()).toLocalDate();
    java.time.LocalDate out = new java.sql.Date(checkOut.getTime()).toLocalDate();

    return (int) java.time.temporal.ChronoUnit.MONTHS.between(in, out);
}
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       clearFields();
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void clearFields() {
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jComboBox1.setSelectedIndex(0);
    jComboBox2.setSelectedIndex(0);
    jComboBox3.setSelectedIndex(0);
    jSpinner1.setValue(0);
    jDateChooser1.setDate(null);
    jDateChooser2.setDate(null);
}
    private void addTenant() {
    try {
        String name = jTextField1.getText().trim();
        String contact = jTextField3.getText().trim();
        String address = jTextField2.getText().trim();
        String gender = jComboBox1.getSelectedItem().toString();
        String payment = jComboBox3.getSelectedItem().toString().toLowerCase();

        if (name.isEmpty() || contact.isEmpty() || address.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all text fields.");
            return;
        }

        if (gender.equals("Select")) {
            JOptionPane.showMessageDialog(this, "Please select gender.");
            return;
        }

        if (jComboBox2.getSelectedItem().toString().equals("Select")) {
            JOptionPane.showMessageDialog(this, "Please select a room.");
            return;
        }

        if (jComboBox3.getSelectedItem().toString().equals("Select")) {
            JOptionPane.showMessageDialog(this, "Please select payment status.");
            return;
        }

        if (jDateChooser1.getDate() == null || jDateChooser2.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please select check-in and check-out dates.");
            return;
        }

        int age = (int) jSpinner1.getValue();

        if (age <= 0) {
            JOptionPane.showMessageDialog(this, "Age must be greater than 0.");
            return;
        }

        int roomId = Integer.parseInt(jComboBox2.getSelectedItem().toString());

        java.util.Date checkIn = jDateChooser1.getDate();
        java.util.Date checkOut = jDateChooser2.getDate();

        if (!checkOut.after(checkIn)) {
            JOptionPane.showMessageDialog(this, "Check-out date must be after check-in date.");
            return;
        }

        int months = calculateMonths(checkIn, checkOut);
        jTextField4.setText(String.valueOf(months));

        java.sql.Connection conn = DBConnection.getConnection();

        String checkRoom = "SELECT occupied, capacity FROM rooms WHERE id=?";
        PreparedStatement pstCheck = conn.prepareStatement(checkRoom);
        pstCheck.setInt(1, roomId);
        ResultSet rsCheck = pstCheck.executeQuery();

        if (rsCheck.next()) {
            int occupied = rsCheck.getInt("occupied");
            int capacity = rsCheck.getInt("capacity");

            if (occupied >= capacity) {
                JOptionPane.showMessageDialog(this, "Room is FULL!");
                return;
            }
        }

        String sql = "INSERT INTO tenants "
                + "(name, contact, address, gender, age, room_id, check_in, check_out, months_stayed, payment_status) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        PreparedStatement pst = conn.prepareStatement(sql, java.sql.Statement.RETURN_GENERATED_KEYS);

        pst.setString(1, name);
        pst.setString(2, contact);
        pst.setString(3, address);
        pst.setString(4, gender);
        pst.setInt(5, age);
        pst.setInt(6, roomId);
        pst.setDate(7, new java.sql.Date(checkIn.getTime()));
        pst.setDate(8, new java.sql.Date(checkOut.getTime()));
        pst.setInt(9, months);
        pst.setString(10, payment);

        pst.executeUpdate();

        ResultSet keys = pst.getGeneratedKeys();
        int tenantId = 0;

        if (keys.next()) {
            tenantId = keys.getInt(1);
        }

        PreparedStatement updateRoom = conn.prepareStatement(
                "UPDATE rooms SET occupied = occupied + 1 WHERE id=?"
        );
        updateRoom.setInt(1, roomId);
        updateRoom.executeUpdate();

        logHistory(tenantId, "ADD", "Added tenant " + name + " to room " + roomId);

        JOptionPane.showMessageDialog(this, "Tenant Added Successfully!");

        loadTenantsTable();
        loadRoomsToComboBox();
        clearFields();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error adding tenant: " + e.getMessage());
    }
}
    
    private void loadTenantsTable() {
    try {
        javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        java.sql.Connection conn = DBConnection.getConnection();

        String sql = "SELECT * FROM tenants ORDER BY id DESC";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("name"),
                rs.getString("contact"),
                rs.getString("address"),
                rs.getString("gender"),
                rs.getInt("age"),
                rs.getInt("room_id"),
                rs.getDate("check_in"),
                rs.getDate("check_out"),
                rs.getInt("months_stayed"),
                rs.getString("payment_status")
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading tenants: " + e.getMessage());
    }
}
    private void deleteTenant() {
    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Select a row first!");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this tenant?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    try {
        int tenantId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
        String name = jTable1.getValueAt(selectedRow, 1).toString();
        int roomId = Integer.parseInt(jTable1.getValueAt(selectedRow, 6).toString());

        java.sql.Connection conn = DBConnection.getConnection();

        logHistory(tenantId, "DELETE", "Deleted tenant " + name + " from room " + roomId);

        String sql = "DELETE FROM tenants WHERE id=?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, tenantId);
        pst.executeUpdate();

        PreparedStatement updateRoom = conn.prepareStatement(
                "UPDATE rooms SET occupied = occupied - 1 WHERE id=? AND occupied > 0"
        );
        updateRoom.setInt(1, roomId);
        updateRoom.executeUpdate();

        JOptionPane.showMessageDialog(this, "Deleted Successfully!");

        loadTenantsTable();
        loadRoomsToComboBox();
        clearFields();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error deleting tenant: " + e.getMessage());
    }
}  
    private void loadRoomsToComboBox() {
    try {
        jComboBox2.removeAllItems();
        jComboBox2.addItem("Select");

        java.sql.Connection conn = DBConnection.getConnection();

        // Only show available rooms
        String sql = "SELECT id FROM rooms WHERE status = 'Available'";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            jComboBox2.addItem(String.valueOf(rs.getInt("id")));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading rooms: " + e.getMessage());
    }
}
    private void updateTenant() {
    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Select a row first!");
        return;
    }

    try {
        int tenantId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
        int oldRoomId = Integer.parseInt(jTable1.getValueAt(selectedRow, 6).toString());

        String name = jTextField1.getText().trim();
        String contact = jTextField3.getText().trim();
        String address = jTextField2.getText().trim();
        String gender = jComboBox1.getSelectedItem().toString();
        int age = (int) jSpinner1.getValue();
        int newRoomId = Integer.parseInt(jComboBox2.getSelectedItem().toString());

        java.util.Date checkIn = jDateChooser1.getDate();
        java.util.Date checkOut = jDateChooser2.getDate();

        int months = calculateMonths(checkIn, checkOut);
        String payment = jComboBox3.getSelectedItem().toString().toLowerCase();

        java.sql.Connection conn = DBConnection.getConnection();

        String sql = "UPDATE tenants SET name=?, contact=?, address=?, gender=?, age=?, room_id=?, "
                + "check_in=?, check_out=?, months_stayed=?, payment_status=? WHERE id=?";

        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, name);
        pst.setString(2, contact);
        pst.setString(3, address);
        pst.setString(4, gender);
        pst.setInt(5, age);
        pst.setInt(6, newRoomId);
        pst.setDate(7, new java.sql.Date(checkIn.getTime()));
        pst.setDate(8, new java.sql.Date(checkOut.getTime()));
        pst.setInt(9, months);
        pst.setString(10, payment);
        pst.setInt(11, tenantId);

        pst.executeUpdate();

        if (oldRoomId != newRoomId) {
            PreparedStatement minusOldRoom = conn.prepareStatement(
                    "UPDATE rooms SET occupied = occupied - 1 WHERE id=? AND occupied > 0"
            );
            minusOldRoom.setInt(1, oldRoomId);
            minusOldRoom.executeUpdate();

            PreparedStatement addNewRoom = conn.prepareStatement(
                    "UPDATE rooms SET occupied = occupied + 1 WHERE id=?"
            );
            addNewRoom.setInt(1, newRoomId);
            addNewRoom.executeUpdate();
        }

        logHistory(tenantId, "UPDATE", "Updated tenant " + name);

        JOptionPane.showMessageDialog(this, "Updated Successfully!");

        loadTenantsTable();
        loadRoomsToComboBox();
        clearFields();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error updating tenant: " + e.getMessage());
    }
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tenants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tenants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tenants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tenants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tenants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDasboard;
    private javax.swing.JButton btnHistory1;
    private javax.swing.JButton btnPayments;
    private javax.swing.JButton btnRooms;
    private javax.swing.JButton btnTenants;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
